### DISCUSSION TITLE
How to use zx in GitHub Actions?

### DISCUSSION THREAD

**Discussion by budarin** [google/zx#237] [Help needed] [answered]
How to use zx in GitHub Actions?

**Comment by antongolub** [comment, marked as answer]
```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build
      env:
        FORCE_COLOR: 3
      run: |
        npx zx <<'EOF'
        await $`...`
        EOF
```
