### DISCUSSION TITLE
How to use a templating tool? something like envsubst

### DISCUSSION THREAD

**Discussion by lacherogwu** [google/zx#562] [Help needed]
Let's say for example I have yaml files with variables

```yaml
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: ${CLUSTER_NAME}-frontend-backendconfig
spec:
  timeoutSec: 60
  connectionDraining:
    drainingTimeoutSec: 30
  securityPolicy:
    name: '${SECURITY_POLICY_NAME}'
```

on bash I can do `envsubst < file.yaml` and have the env vars available

I am interested if there's a recommended way to to it using zx
