### ISSUE TITLE
build: omit redundant pkgjson fields on publishing

### ISSUE THREAD

**Issue by antongolub** [google/zx#1003]
Smth like [clean-publish](https://github.com/shashkovdanil/clean-publish) is required but w/o overengineering. Simple `scripts/clean-pkg-json.mjs` seems enough.

1) We use bundling, so there's no need to keep any deps except the `optionalDependencies`
2) Prettier config section should be flushed
3) We dont have pre or post-install scripts, so the whole section can be dropped

**Comment by easymikey** [comment]
How to use prettier in this case? Create other config or use default config settings?

**Comment by antongolub** [comment]
**npm-publish.yml**
```yaml
...
- run: node scripts/clean-pkg-json.mjs
- run: echo "//wombat-dressing-room.appspot.com/:_authToken=$AUTH_TOKEN" >> .npmrc
  env:
    AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
- run: npm publish --provenance --access=public
```

**scripts/clean-pkg-json.mjs**
```js
import fs from 'node:fs'
import path from 'node:path'

const __dirname = // ...
const filepath = path.resolve(__dirname, '../package.json')

const pkgJson = JSON.parse(fs.readFileSync(filepath))
const cleaned = {
   ...pkgJson,
   prettier: undefined,
   scripts: undefined,
   devDependencies: undefined
}

fs.writeFileSync(filepath, JSON.stringify(filepath, null, 2))
```

Or even 

```json
{
   "prepublish": "node scripts/clean-pkg-json.mjs"
}
```
