### ISSUE TITLE
feat: provide configuration via env vars

### ISSUE THREAD

**Issue by antongolub** [google/zx#973]
When zx script becomes a part of cicd pipeline/container its parameterization may lose readability, but env map will be much clearer:

```yaml
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        run: npx some-zx-based-tool
        env:
          ZX_VERBOSE: true
          ZX_SHELL: /some/custom/shell/path
```
